export const shopCategories = [
  { value: "toys", label: "Toys & Games" },
  { value: "electronics", label: "Electronics" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "home", label: "Home & Living" },
  { value: "furniture", label: "Furniture" },
  { value: "groceries", label: "Groceries & Food" },
  { value: "health", label: "Health & Wellness" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "books", label: "Books & Stationery" },
  { value: "automotive", label: "Automotive" },
  { value: "baby", label: "Baby & Kids" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "pet-supplies", label: "Pet Supplies" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "tools", label: "Tools & Hardware" },
  { value: "office", label: "Office Supplies" },
  { value: "music", label: "Music & Instruments" },
  { value: "crafts", label: "Arts & Crafts" },
  { value: "travel", label: "Travel & Luggage" },
  { value: "shoes", label: "Shoes & Footwear" },
  { value: "appliances", label: "Appliances" },
  { value: "mobile", label: "Mobile Phones & Accessories" },
  { value: "computers", label: "Computers & Accessories" },
  { value: "gifts", label: "Gifts & Occasions" },
  { value: "other", label: "Other" },
];
